runtime: node:18.7.0

handlers:
  - url: /.*
  secure: always
  redirect_http_response_code: 301
  static_files: dist/ui/index.html
  upload: dist/ui/index.html
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Frame-Options: DENY 